apiVersion: apiserver.config.k8s.io/v1beta1
kind: AuthenticationConfiguration
jwt:
  - issuer: 
      url: https://accounts.google.com
      audiences:
        - YOUR-CLIENT-ID
      audienceMatchPolicy: MatchAny
    claimMappings:
      username:
        claim: email
        prefix: ""